require('dotenv').config()
// const {Configuration, OpenAIApi} = require('openai');
const express = require('express')
const mongoose = require('mongoose')
const usersRoute = require('./routes/users')
const bodyParser = require('body-parser');
const cors = require('cors');
const { OpenAI } = require('openai');

const app = express()
app.use(bodyParser.json());
app.use(cors());

const openai = new OpenAI({apiKey: process.env.API_TOKEN});

app.use(express.json())
// middleware
app.use((req, res, next) => {
    console.log(req.path, req.method)
    next()
})

// routes
app.use('/api/users', usersRoute)

app.post('/api/users/message', async (req, res) => {
    // New
    // await openai.completions.create({
    //     model: 'gpt-3.5-turbo-instruct',
    //     // model: 'gpt-3.5-turbo-instruct-0914',
    //     prompt: req.body.message,
    //     temperature: 0,
    //     top_p: 1,
    //     frequency_penalty: 0,
    //     presence_penalty: 0,
    //     max_tokens: 30
    // }).then((data) => {
    //     const message = {message: data.data.choices[0].text};
    //     res.send(message);
    // });
    const msg = "This message is autogenerated since CHATGPT api tokens are now only accessible by a paid plan";
    res.send({message: msg});
});

// connect to mongo
mongoose.connect(process.env.MONGO_URL).then(() => {
    app.listen(process.env.PORT, () => {
        console.log('listen on port and mongoose', process.env.PORT)
    })
}).catch((err) => {
    console.log(err)
})
